### ISSUE TITLE
[FE] - Application logo not reflecting latest design 

### ISSUE THREAD

**Issue by repo-explorer** [Jaydip14/Hello-World#2]
Our application logo is not aligning properly in the latest development site.

Please see the below screen shot for more information.

![image](https://user-images.githubusercontent.com/126343523/221368604-cb95e335-7e80-446b-83a0-d3ab2e6f84ff.png)

**Expected Result**: - Application should render the correct logo.
**Actual Result**: - Application is rendering the outdated logo.

**Comment by Jaydip14** [comment]
Raised Pull request: - https://github.com/Jaydip14/Hello-World/pulls
@repo-explorer - Please start the verification after the latest deployment.

**Comment by repo-explorer** [comment]
@Jaydip14 - I 'm still seeing the issue. Reopening the ticket.

Please refer to the attached screenshot.


![Image](https://user-images.githubusercontent.com/126343523/221369403-0762a064-8277-4dc3-92a4-7f7168baaa70.png)

**Comment by Jaydip14** [comment]
Fixed. New PR Url:- https://github.com/Jaydip14/Hello-World

@repo-explorer - Please start verification after deployment.
